name       : jsoncpp
version    : 1.8.4
release    : 4
source     :
    - https://github.com/open-source-parsers/jsoncpp/archive/1.8.4.tar.gz : c49deac9e0933bcb7044f08516861a2d560988540b23de2ac1ad443b219afdb6
license    : MIT
component  : programming.library
summary    : A C++ library for interacting with JSON.
description: |
    JsonCpp is a C++ library that allows manipulating JSON values, including serialization and deserialization to and from strings. It can also preserve existing comment in unserialization/serialization steps, making it a convenient format to store user input files.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
