name       : jsoncpp
version    : 0.10.5
release    : 2
source     :
    - https://github.com/open-source-parsers/jsoncpp/archive/0.10.5.tar.gz : 56afb14d2ef1c52e72771a221346d4b94f0d46d4e67f796bbcaedb176ca823df
license    : MIT
summary    : A C++ library for interacting with JSON.
description: |
    A C++ library for interacting with JSON.
setup      : |
    %cmake -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=OFF .
build      : |
    %make
install    : |
    %make_install
