name       : jsoncpp
version    : 1.7.5
release    : 3
source     :
    - https://github.com/open-source-parsers/jsoncpp/archive/1.7.5.tar.gz : 4338c6cab8af8dee6cdfd54e6218bd0533785f552c6162bb083f8dd28bf8fbbe
license    : MIT
summary    : A C++ library for interacting with JSON.
description: |
    A C++ library for interacting with JSON.
setup      : |
    %cmake -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=OFF .
build      : |
    %make
install    : |
    %make_install
