name       : jsoncpp
version    : 1.9.5
release    : 5
source     :
    - https://github.com/open-source-parsers/jsoncpp/archive/1.9.5.tar.gz : f409856e5920c18d0c2fb85276e24ee607d2a09b5e7d5f0a371368903c275da2
license    : MIT
component  : programming.library
summary    : A C++ library for interacting with JSON.
description: |
    JsonCpp is a C++ library that allows manipulating JSON values, including serialization and deserialization to and from strings. It can also preserve existing comment in unserialization/serialization steps, making it a convenient format to store user input files.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
